version: "3"

services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
    - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    image: registry.gitlab.com/stelmakhov/testtask:master
    ports:
      - 8080:8080
    depends_on:
      - webserver
